blank_issues_enabled: true
contact_links:
  - name: Create new issue
    url: https://zouyaoji.top/issue-generator/#/zh-CN
    about: The issue which is not created via https://zouyaoji.top/issue-generator will be closed immediately.
