name: Deploy Doc Website
on:
  push:
    branches:
      - master

jobs:
  master-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: npm install

      - name: Build Docs
        run: npm run build:docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          GIT_CONFIG_NAME: zouyaoji
          GIT_CONFIG_EMAIL: 370681295@qq.com
          COMMIT_MESSAGE: website deploy
